env:
  browser: true
  commonjs: true
  es6: true
  jasmine: true
  node: true
plugins: ["wdio"]
extends: 'plugin:wdio/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  browser: readonly
  webdriver: readonly
  $: readonly
  $$: readonly
  suite: readonly
  test: readonly
  by: readonly
  By: readonly
  driver: readonly
  element: readonly
  jQuery: readonly
  document: readonly
  protractor: readonly
  ui5: readonly
  non_ui5: readonly
  oData: readonly
  odata: readonly
  utilities: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  keyword-spacing: 2
  indent: [2, 2, {ignoreComments: true, SwitchCase: 1}]
  no-console: 1
  no-const-assign: 2
  no-extra-semi: 2
  no-irregular-whitespace: 2
  no-redeclare: 2
  no-undef: 2
  no-unused-expressions: 2
  quotes: [2, 'double', {avoidEscape: true, allowTemplateLiterals: true}]
  prefer-const: 1
  semi: [2, 'always']
