site_name: Qmate-Service
site_author: D056896
nav:
  - Home: index.md
  - Reuse API: doc.md
  - Setup & Installation:
    - Qmate-Service Installation: topics/setupAndInstallation.md
  - Native Features: topics/nativeFeatures.md
  - Custom Features:
    - Reuse: topics/reuse.md
    - Authentication:  topics/authentication.md
    - Data Exchange: topics/dataImportExport.md
    - OData: https://pages.github.tools.sap/sProcurement/qmate/topics/furtherTopics/odata/
  - Custom Services:
    - reporter-service: https://github.tools.sap/sProcurement/wdio-qmate-reporter-service
    - bo-reuse-service: https://github.tools.sap/sProcurement/wdio-qmate-bo-reuse-service
    - code-coverage-service: https://github.tools.sap/sProcurement/wdio-qmate-code-coverage-service
  - Selectors: https://pages.github.tools.sap/sProcurement/qmate/topics/gettingStarted/selectors/
  - Contact: topics/contact.md
theme:
  name: material
  features:
    - content.code.annotate 
    - content.tabs.link
    - navigation.top
  palette:
    - scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - 'javascripts/extra.js'
extra_css:
  - 'css/extra.css'
docs_dir: documentation
site_dir: docs-gen
repo_url: https://github.tools.sap/sProcurement/wdio-qmate-service
site_url: https://github.tools.sap/pages/sProcurement/wdio-qmate-service
edit_uri: main/documentation/